version: "3"

services:
  backend:
    container_name: bank_rest
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    env_file:
      - .env

  postgresql:
    container_name: bank_rest_db
    image: "postgres:16.0"
    restart: always
    volumes:
      - bank_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  bank_db-data: